# This workflow contains all testing/plans used on PRs
name: Plan UDS Environments

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - prod

permissions:
  contents: write
  id-token: write
  pull-requests: write
  packages: read

jobs:
  plan_changes:
    name: Plan UDS Environment Changes
    uses: ./.github/workflows/plan-environment-callable.yaml
    with:
      environment: ${{ github.repository == 'mxnxpx-org/workflow-test-upstream' && 'btb' || github.repository == 'MxNxPx/workflow-test-fork' && 'prod' }}
#      environment: ${{ github.repository == 'defenseunicorns/uds-infrastructure' && 'btb' || github.repository == 'defenseunicorns/uds-infrastructure-prod' && 'prod' }}
    secrets: inherit # Inherits all secrets from the parent workflow.
